### PR TITLE
[Bug]: "0" is interpreted as "--EMPTY--" in transformation pipeline

### LINKED ISSUE #211: [Bug]: "0" is interpreted as "--EMPTY--" in transformation pipeline
### Expected behavior

"0" should be a valid value

### Actual behavior

"0" is recognized as "--EMPTY--"

image

### Steps to reproduce

1.) Add e.g. "ObjectKey 0" as value to a column
2.) Use e.g. string replace to remove "ObjectKey "
3.) Check transformation pipeline preview

### PR DESCRIPTION
**Pull request by robertSt7**
resolve #211

### CODE REVIEW

File: src/Processing/ImportProcessingService.php [hunk 1]
```diff
@@ -331,7 +331,9 @@ public function generateTransformationResultPreview(array $importDataRow, Mappin
             $data = $operator->generateResultPreview($data);
         }
 
-        if (empty($data)) {
+        if ($data === '0') {
+            return '0';
+        } elseif (empty($data)) {
             return '-- EMPTY --';
         } elseif (is_string($data)) {
             return $data;
```
Comment (mcop1) [inline src/Processing/ImportProcessingService.php]:
```suggestion
       if (is_string($data) && $data !== '') {
            return $data;
        } elseif (empty($data)) {
            return '-- EMPTY --';
```
@robertSt7 Maybe it would be a good idea to rearrange the statements, add the check for empty string and spare the additonal if condition. Wdyt?

**Review by mcop1 — APPROVED** [review]
