### PR TITLE
Fix Data Mapping checks for empty fields

### LINKED ISSUE #348: [Bug]: Gallery Operator does not work properly when you uncheck "Overwrite: if target is not empty"
### Expected behavior

When a transform pipeline results in a Gallery and _Overwrite: if target is not empty_ in DataTarget (Direct) is **unchecked** (default: checked), it should import/assign images to the ImageGallery concerned, if there were no items in the ImageGallery before

### Actual behavior

When _Overwrite: if target is not empty_ in DataTarget (Direct) is **unchecked**, no images are imported when an empty gallery exists (which seems to be the case as soon as an object was saved before)

### Steps to reproduce

1.  add a ImageGallery to a Class definition
2. create an Object of that class and save it (with no images in the gallery)
3. create an import definition with a transformation pipeline resulting in a gallery (by using `Gallery` Operator)
4. Use _DataTarget_  `Direct` and **uncheck** _Overwrite: if target is not empty_
5. Run an import which assings images to the gallery
=> no images are assigned, no error

My guess: there should be an check if `$currentData->getIems()` is empty (if gallery or if that mehtod exists) here
https://github.com/pimcore/data-importer/blob/1.x/src/Mapping/DataTarget/Direct.php#L140

### PR DESCRIPTION
**Pull request by dvesh3**
Resolves #348

### CODE REVIEW

File: src/Mapping/DataTarget/Direct.php [hunk 1]
```diff
@@ -137,13 +138,49 @@ protected function checkAssignData($newData, $valueContainer, $getter)
         $currentData = $valueContainer->$getter($this->language);
         DataObject::setHideUnpublished($hideUnpublished);
 
-        if (!empty($currentData) && $this->writeIfTargetIsNotEmpty === false) {
+        $fieldName = lcfirst(str_replace('get', '', $getter));
+        $fieldDefinition = $this->getFieldDefinition($valueContainer, $fieldName);
+        if (!$fieldDefinition->isEmpty($currentData) && $this->writeIfTargetIsNotEmpty === false) {
```
Comment (blankse) [inline src/Mapping/DataTarget/Direct.php]:
```suggestion
        if ($this->writeIfTargetIsNotEmpty === false && !$fieldDefinition->isEmpty($currentData)) {
```

File: src/Mapping/DataTarget/Direct.php [hunk 2]
```diff
@@ -137,13 +138,49 @@ protected function checkAssignData($newData, $valueContainer, $getter)
...
+        if ($this->writeIfSourceIsEmpty === false && $fieldDefinition->isEmpty($newData)) {
             return false;
         }
 
         return true;
     }
+
+    /**
+     * @param DataObject\Concrete|DataObject\Objectbrick\Data\AbstractData $valueContainer
+     * @param string $fieldName
```
Comment (robertSt7) [inline src/Mapping/DataTarget/Direct.php:156]: @dvesh3 Why do we have docs there, when we can do this in the parameter types?

Comment (dvesh3) [reply src/Mapping/DataTarget/Direct.php:156]: doesn't work with typehint as `checkAssignData` defines `Object` for `$valueContainer` so better introduce it with major version change the typehint for `checkAssignData` as well (bc break).
