### PR TITLE
[Bug]: Element Loading Strategy not working if it is an Object Brick's attribute

### LINKED ISSUE #95: [Bug]: Element Loading Strategy not working if it is an Object Brick's attribute
### Expected behavior

When creating a profile in the Data Hub Import, if I choose Attribute for Element Loading Strategy and choose an attribute from an object brick in the Attribute Name field, then I expect it to load element correctly.

### Actual behavior

Running the process fails with exception

[pimcore] Class: DataObject\Concrete => call to undefined static method getByMoreDetails.SupplierRecmar.Reference
16:19:53 ERROR     [DATA-IMPORTER] Error processing element: Exception: Call to undefined static method getByMoreDetails.SupplierRecmar.Reference in class DataObject\Concrete in /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php:764
Stack trace:
#0 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Load/AttributeStrategy.php(76): Pimcore\Model\DataObject\Concrete::__callStatic('getByMoreDetail...', Array)
#1 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Load/AbstractLoad.php(86): Pimcore\Bundle\DataImporterBundle\Resolver\Load\AttributeStrategy->loadElementByIdentifier('EPL-593XX')
#2 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Resolver.php(159): Pimcore\Bundle\DataImporterBundle\Resolver\Load\AbstractLoad->loadElement(Array)
#3 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Resolver.php(179): Pimcore\Bundle\DataImporterBundle\Resolver\Resolver->loadElement(Array)
#4 /var/www/html/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(162): Pimcore\Bundle\DataImporterBundle\Resolver\Resolver->loadOrCreateAndPrepareElement(Array)
#5 /var/www/html/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(141): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processElement('TEST1', Array, Object(Pimcore\Bundle\DataImporterBundle\Resolver\Resolver), Array)
#6 /var/www/html/vendor/pimcore/data-importer/src/Command/SequentialProcessQueueCommand.php(63): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processQueueItem(242810)
#7 /var/www/html/vendor/symfony/console/Command/Command.php(299): Pimcore\Bundle\DataImporterBundle\Command\SequentialProcessQueueCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(996): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\SequentialProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/console/Application.php(295): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\SequentialProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/bin/console(46): Symfony\Component\Console\Application->run()
#14 {main}

### Steps to reproduce

1. Create data hub  importer profile
2. In Element Loading Strategy, choose Attribute and pick an Object Brick's attribute in the Attribute Name field
3. Run import 
image

### PR DESCRIPTION
**Pull request by mcop1**
fixes #95

### CODE REVIEW

File: src/Mapping/Operator/AbstractOperator.php [hunk 1]
```diff
@@ -34,7 +35,7 @@ abstract class AbstractOperator implements OperatorInterface
      *
      * @param ApplicationLogger $applicationLogger
      */
-    public function __construct(ApplicationLogger $applicationLogger)
+    public function __construct(ApplicationLogger $applicationLogger, protected DataObjectLoader $dataObjectLoader)
```
Comment (fashxp) [inline src/Mapping/Operator/AbstractOperator.php]: do we really need that in the abstract? as the dataobjetloader is only needed in a couple of operators?

File: src/Tool/DataObjectLoader.php [hunk 2]
```diff
@@ -0,0 +1,144 @@
...
+    const BRICK_ATTRIBUTE_SEPARATOR = '.';
+
+    /**
+     * @param string $attributeName
+     *
+     * @return bool
+     */
+    private function isObjectBrickAttribute(string $attributeName): bool
+    {
+        return str_contains($attributeName, '.');
```
Comment (fashxp) [inline src/Tool/DataObjectLoader.php]: why not use `BRICK_ATTRIBUTE_SEPARATOR` ... if we have it already?

**Review by fashxp — CHANGES_REQUESTED** [review]

File: src/Mapping/Operator/AbstractOperator.php (hunk 1 above)
Comment (mcop1) [reply src/Mapping/Operator/AbstractOperator.php]: Moved it to LoadDataObject.php

**Review by fashxp — APPROVED** [review]
