### PR TITLE
Fix too many connections error on import

### LINKED ISSUE #354: [Feature]: [Bug]: too many connections mysql error when import data through datahub importer
### Feature description

[Bug]: too many connections mysql error when import data through datahub importer, I think missing of garbageCollector

### PR DESCRIPTION
**Pull request by dvesh3**
Resolves #354

### CODE REVIEW

File: src/Command/ParallelProcessQueueCommand.php [hunk 1]
```diff
@@ -68,5 +68,10 @@ protected function doFetchItems(InputInterface $input, ?OutputInterface $output)
     protected function runSingleCommand(string $item, InputInterface $input, OutputInterface $output): void
     {
         $this->importProcessingService->processQueueItem((int) $item);
+
+        // call the garbage collector if memory consumption is > 100MB
+        if (memory_get_usage() > 100000000) {
```
Comment (fashxp) [inline src/Command/ParallelProcessQueueCommand.php]: is that really necessary? 
actually, that should already be done by https://github.com/pimcore/pimcore/blob/11.x/lib/Console/Traits/Parallelization.php#L61

Comment (fashxp) [reply src/Command/ParallelProcessQueueCommand.php]: maybe we should consider batch sizes somehow, when there is no `\Webmozarts\Console\Parallelization` in here: https://github.com/pimcore/pimcore/blob/11.x/lib/Console/Traits/ParallelizationBase.php#L44

File: src/Messenger/DataImporterHandler.php [hunk 2]
```diff
@@ -50,8 +50,13 @@ public function __construct(
 
     public function __invoke(DataImporterMessage $message)
     {
-        foreach ($message->getIds() as $id) {
+        foreach ($message->getIds() as $i => $id) {
             $this->importProcessingService->processQueueItem($id);
+
+            // call the garbage collector to avoid too many connections & memory issue
+            if (($i + 1) % 200 === 0) {
```
Comment (fashxp) [inline src/Messenger/DataImporterHandler.php]: not needed, as worker item count is 200 by default anyway: https://github.com/pimcore/data-importer/blob/1.x/src/DependencyInjection/Configuration.php#L53

so, by default in one message, there should not be more than 200 items anyway.

**Review by fashxp — CHANGES_REQUESTED** [review]

File: src/Command/ParallelProcessQueueCommand.php (hunk 1 above)
Comment (dvesh3) [reply src/Command/ParallelProcessQueueCommand.php]: Reverted. please see https://github.com/pimcore/pimcore/issues/16065

File: src/Messenger/DataImporterHandler.php (hunk 2 above)
Comment (dvesh3) [reply src/Messenger/DataImporterHandler.php]: what about the cases where `worker_item_count` is set higher in config?

Comment (dvesh3) [reply src/Messenger/DataImporterHandler.php]: @fashxp wdyt?

Comment (fashxp) [reply src/Messenger/DataImporterHandler.php]: if this leads to problems, the developer needs to reduce it again :-)
the whole point of that worker_item_count is to prevent these kind of problems... memory, long running processes, etc.

Comment (dvesh3) [reply src/Messenger/DataImporterHandler.php]: Reverted. thanks!
