### PR TITLE
[Bug]: Error using "As input quantity value" mapper 

### LINKED ISSUE #340: [Bug]: Error using "As input quantity value" mapper
### Expected behavior

Map an input field as input quantity value with a static unit

### Actual behavior

Throws this exception:
`Status: 500 | Internal Server Error
URL: /admin/pimcoredataimporter/dataobject/config/load-transformation-result
Method: POST
Message: Attempted to call an undefined method named "setSettings" of class "Pimcore\Bundle\DataImporterBundle\Mapping\Operator\Factory\InputQuantityValue".
Trace: 
in /var/www/html/vendor/pimcore/data-importer/src/Mapping/MappingConfigurationFactory.php:69
#0 /var/www/html/vendor/pimcore/data-importer/src/Mapping/MappingConfigurationFactory.php(132): Pimcore\Bundle\DataImporterBundle\Mapping\MappingConfigurationFactory->buildTransformationPipeline('Product', Array)
#1 /var/www/html/vendor/pimcore/data-importer/src/Mapping/MappingConfigurationFactory.php(111): Pimcore\Bundle\DataImporterBundle\Mapping\MappingConfigurationFactory->loadMappingConfigurationItem('Product', Array, true)
#2 /var/www/html/vendor/pimcore/data-importer/src/Controller/ConfigDataObjectController.php(386): Pimcore\Bundle\DataImporterBundle\Mapping\MappingConfigurationFactory->loadMappingConfiguration('Product', Array, true)
#3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(166): Pimcore\Bundle\DataImporterBundle\Controller\ConfigDataObjectController->loadTransformationResultPreviewsAction(Object(Symfony\Component\HttpFoundation\Request), Object(Pimcore\Bundle\DataImporterBundle\Settings\ConfigurationPreparationService), Object(Pimcore\Bundle\DataImporterBundle\Mapping\MappingConfigurationFactory), Object(Pimcore\Bundle\DataImporterBundle\DataSource\Interpreter\InterpreterFactory), Object(Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService))
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#8 /var/www/html/public/index.php(19): require_once('/var/www/html/v...')
#9 {main}
`

### Steps to reproduce

1. Create an import Job
2. Use CSV as file extension, semi-colon as delimiter
3. Add a mapping with a string input field
4. Select "as input quantity value" as Data Type inside Transformation Pipelines

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #340

### CODE REVIEW

File: src/Mapping/Operator/Factory/InputQuantityValue.php [hunk 1]
```diff
@@ -24,11 +24,11 @@ class InputQuantityValue extends QuantityValue
      * @param mixed $inputData
      * @param bool $dryRun
      *
-     * @return \Pimcore\Model\DataObject\Data\QuantityValue
+     * @return \Pimcore\Model\DataObject\Data\InputQuantityValue
      */
     public function process($inputData, bool $dryRun = false)
     {
-        return new \Pimcore\Model\DataObject\Data\QuantityValue(
+        return new \Pimcore\Model\DataObject\Data\InputQuantityValue(
```
Comment (kingjia90) [inline src/Mapping/Operator/Factory/InputQuantityValue.php:34]: without this commit, the import process fails 
image

File: src/Mapping/Operator/Factory/InputQuantityValue.php [hunk 2]
```diff
@@ -59,8 +65,10 @@ public function evaluateReturnType(string $inputType, int $index = null): string
      */
     public function generateResultPreview($inputData)
     {
-        if ($inputData instanceof \Pimcore\Model\DataObject\Data\QuantityValue) {
-            return 'InputQuantityValue: ' . $inputData->getValue() . ' ' . ($inputData->getUnit() ? $inputData->getUnit()->getAbbreviation() : '');
+        if ($inputData instanceof \Pimcore\Model\DataObject\Data\InputQuantityValue) {
+            return 'InputQuantityValue: ' .
+                $inputData->getValue() . ' ' .
+                ($inputData->getUnit() ? '['.$inputData->getUnit()->getAbbreviation().']' : '');
```
Comment (kingjia90) [inline src/Mapping/Operator/Factory/InputQuantityValue.php]: only `unitId` would be set when passing a `string` in constructor and here would only appear the value without the unit

https://github.com/pimcore/pimcore/blob/89d0af7753f242378c22aab19ec00f678be3d780/models/DataObject/Data/AbstractQuantityValue.php#L48

**Comment by kingjia90** [comment]
not sure about the changes 🤔 but works and looks more in line with latest implementations.
In the core, there are `Model/QuantityValue` and `Model/InputQuantityValue`, that both extend `AbstractQuantityValue`, while here (before PR) in the importer `Operator/InputQuantityValue` extends `Operator/QuantityValue`, as if it's an alias/shortcut to directly pass the `unit` as string. 
It feels like some refactoring in the core (AbstractQuantityValue) didn't got the follow-up in this bundle, maybe due BC
