### PR TITLE
Can't save Data Objects Importer Configuration on Pimcore 6.9.x and data-importer 1.3.1

### LINKED ISSUE #125: [Bug]: Can't save Data Objects Importer Configuration on Pimcore 6.9.x and data-importer 1.3.1
### Expected behavior

data-importer Data Objects Importer Configuration can be saved (on pimcore 6.9.x).

### Actual behavior

data-importer Data Objects Importer Configuration Save Buttons is disabled and grayed out with the tooltip "config_not_writeable", for new and existing Configurations.

Screenshot 2021-11-17 at 12 38 29

### Steps to reproduce

1. install data-importer 1.3.1 on the latest pimcore 6.9.x
2. create a new Data Objects Importer Configuration
3. try to save this Configuration
4. save button is disabled and grayed out

the offending commit seems to be https://github.com/pimcore/data-importer/commit/7aa4cfcf25f3bc3587d8423932dd2a6a16d618b0
the commit mentions pimcore 10.2. is pimcore 10.2 a requirement now?
the writeable flag in general within the config is never written or set to true, so it defaults to false/disabled(?).
manually adding the writeable flag in "var/config/datahub-configurations.php" enables the save buttons, but is removed with the next save again.

### PR DESCRIPTION
**Pull request by mcop1**
fixes #125

### CODE REVIEW

**Review by dvesh3 — APPROVED** [review]

File: src/Resources/public/js/pimcore/configuration/configItemDataObject.js [hunk 1]
```diff
@@ -33,6 +33,15 @@ pimcore.plugin.pimcoreDataImporterBundle.configuration.configItemDataObject = Cl
         this.data = data.configuration;
         this.modificationDate = data.modificationDate;
 
+        /**
+         * Set writeable to true, if it is undefined.
+         * This is done because of backwards compatability to version 6.9-
+         * Otherwise the save button would be disabled.
+         */
+        if(this.data.general.writeable === undefined) {
```
Comment (dvesh3) [inline src/Resources/public/js/pimcore/configuration/configItemDataObject.js]:
```suggestion
        if (typeof this.data.general.writeable === 'undefined') {
```
